const SPEAKER_NOTES = {
    1: "<strong>Slide 1: Tiêu đề</strong><br><br>Giới thiệu ngắn: đây là hệ thống gợi ý sản phẩm hai giai đoạn, kết hợp Recall để lấy ứng viên nhanh và Ranking để sắp xếp chính xác hơn.",
    2: "<strong>Slide 2: Bài Toán & Mục Tiêu</strong><br><br>Chốt bài toán trước khi vào kỹ thuật: với user_id và bối cảnh phiên hiện tại, hệ thống trả về Top 20 sản phẩm phù hợp. Ba mục tiêu chính là cá nhân hóa, latency dưới 50ms và tránh leakage khi train/evaluate.",
    3: "<strong>Slide 3: Workflow API</strong><br><br>Request đi vào gồm user_id và session_items. Hệ thống chạy hai kênh recall: long-term user embedding và session vector. Sau đó lấy feature, dùng LightGBM ranker chấm điểm và trả về Top 20.",
    4: "<strong>Slide 4: Phễu Lọc 2 Giai Đoạn</strong><br><br>Đây là ý chính của kiến trúc: không chấm điểm toàn bộ hơn 63 nghìn sản phẩm. FAISS giảm catalog xuống tối đa 200 ứng viên, rồi LightGBM chỉ ranking trên tập nhỏ này.",
    5: "<strong>Slide 5: Recall Model</strong><br><br>PyTorch Matrix Factorization học user embedding và item embedding trong không gian 64 chiều. Sau 5 epochs, embeddings được lưu lại để phục vụ FAISS search.",
    6: "<strong>Slide 6: FAISS & Session Vector</strong><br><br>Session channel lấy session_items từ client, tra item embeddings, average pooling thành session vector, rồi query FAISS IndexFlatIP. Kết quả được gộp với kênh long-term.",
    7: "<strong>Slide 7: LightGBM Ranking</strong><br><br>Ranking không dùng vector thô mà dùng bảng đặc trưng user-item-session. Output là ranking score để sắp xếp ứng viên, không khẳng định là xác suất mua đã calibrated.",
    8: "<strong>Slide 8: Dataset Scale</strong><br><br>Artifact hiện tại dùng 1 triệu log đầu tiên từ dataset eCommerce tháng 10/2019. Quy mô sau khi đọc là 163.024 users và 63.322 sản phẩm độc nhất.",
    9: "<strong>Slide 9: Data Challenges</strong><br><br>Dữ liệu khó ở hai điểm: user-item matrix cực thưa với sparsity 99.9937%, và event bị lệch mạnh về View. Vì vậy cần implicit weights để View, Cart, Purchase có mức tín hiệu khác nhau.",
    10: "<strong>Slide 10: Feature Engineering & Point-in-Time</strong><br><br>LightGBM cần đặc trưng có nghĩa: history bằng cumcount, context bằng session 30 phút, price bằng log-transform. Đồng thời, timeline cho thấy mỗi hàng train chỉ được dùng quá khứ, không dùng future events.",
    11: "<strong>Slide 11: Training Setup</strong><br><br>Recall training dùng negative sampling 1:4, Focal Loss để giảm ảnh hưởng mẫu dễ, và time-based split để mô phỏng dùng quá khứ dự đoán tương lai.",
    12: "<strong>Slide 12: Train-on-Recall</strong><br><br>Ranking được train trên đúng loại candidates mà serving sẽ nhận. Frozen Recall tạo tối đa 200 candidates, sau đó join nhãn: item có tương tác thật là 1, còn item được recall nhưng không tương tác là 0.",
    13: "<strong>Slide 13: Recall Result</strong><br><br>Recall@50 đạt 97.88%, nhưng phải nói rõ đây là train-set sanity check trên artifact huấn luyện. Chỉ số này cho thấy artifact hoạt động, chưa thay thế validation độc lập.",
    14: "<strong>Slide 14: Ranking Result</strong><br><br>Ranking cải thiện so với baseline trên cùng protocol: AUC 0.6375 lên 0.9601, NDCG@10 0.0495 lên 0.0653, MRR 0.0458 lên 0.0572. NDCG/MRR tuyệt đối thấp vì test set rất thưa.",
    15: "<strong>Slide 15: Online Serving</strong><br><br>Smoke benchmark trên 20 user nằm trong recall encoder cho latency trung bình 23.6ms, khoảng 14.8 đến 38.3ms. Feature lookup là phần chiếm nhiều thời gian nhất.",
    16: "<strong>Slide 16: Giới Hạn & Hướng Tiếp Theo</strong><br><br>Nói rõ các caveat để bài bảo vệ chặt hơn: Recall@50 là train-set sanity check, artifact mới train trên 1M log đầu tiên, user/item ngoài encoder cần fallback. Hướng tiếp theo là validation độc lập, mở rộng training, benchmark HTTP thật và cold-start tốt hơn.",
    17: "<strong>Slide 17: Summary & Q/A</strong><br><br>Tổng kết: hệ thống đã chạy end-to-end với dual-channel recall, LightGBM re-ranking, point-in-time features và fallback. Kết thúc bằng Q&A."
};
